Repository dapr/cli, pull requests merged in 2022-03, with the labels that each got.

#894 Upgrade helm version to meet compliance
  go.mod
  go.sum
  pkg/kubernetes/kubernetes.go
Labels: do-not-merge

#852 fix get latest version
  pkg/version/version.go
  pkg/version/version_test.go
Labels: pinned

#931 Adding e2e test for cert renewal with given private key pem file
  pkg/kubernetes/renew_certificate.go
  tests/e2e/common/common.go
  tests/e2e/kubernetes/kubernetes_test.go
  tests/e2e/testdata/example-root.key
Labels: P0, release-blocker

#930 Switching default to Docker Hub and Minor code refactoring
  .github/workflows/self_hosted_e2e.yaml
  pkg/standalone/standalone.go
  pkg/standalone/standalone_test.go
  utils/utils.go
Labels: P0, release-blocker

#903 Added api-log-level flag to log api calls
  .github/workflows/kind_e2e.yaml
  .github/workflows/self_hosted_e2e.yaml
  Makefile
  README.md
  cmd/run.go
  go.mod
  go.sum
  pkg/standalone/run.go
  pkg/standalone/run_test.go
  tests/e2e/standalone/standalone_test.go
  tests/e2e/upgrade/upgrade_test.go
Labels: P0, release-blocker
